remote_theme: openf1/openf1-jekyll-theme

sass:
  style: compressed

collections:
  - sections

exclude: ["CONTRIBUTING.md", "README.md", "LICENSE", "Gemfile*", "script/*"]

links:
  signup_url        : /#
  signin_url        : /#
