remote_theme: openf1/openf1-jekyll-theme

sass:
  style: compressed

collections:
  - sections

exclude: ["CONTRIBUTING.md", "README.md", "LICENSE", "Gemfile*", "script/*"]

links:
  signup_url        : https://openf1.herokuapp.com/accounts/signup
  signin_url        : https://openf1.herokuapp.com/accounts/signin
